version: '2.1'
volumes:
  tor:
  tailscale:
services:
  tor:
    build: ./tor
    container_name: tor
    restart: unless-stopped 
    volumes:
      - tor:/var/lib/tor
  ircd:
    build: ./ircd
    restart: unless-stopped 
    env_file:
      - ircd.env 
    ports:
      - 6667:6667
    container_name: ircd
    volumes:
      - tor:/var/lib/tor
  taud:
    build: ./taud
    restart: unless-stopped 
    env_file:
      - taud.env 
    ports:
      - 23330:23330
    container_name: taud
    volumes:
      - tor:/var/lib/tor
